// Keep the media shopping list true.
//
//   node scripts/media-plan.js            write MEDIA_PLAN.md and the file index
//   node scripts/media-plan.js --check    exit 1 if a page names an id nothing declares
//
// Every screenshot and clip is declared in src/data/features.js or landing.js.
// This reads both, writes MEDIA_PLAN.md (the list to capture and the Remotion
// briefs), and writes src/data/mediaFiles.generated.json: id -> path, for each
// id that already has a file in static/media/. The pages use that index to swap
// a placeholder for the real file with no edit to the page.

'use strict';

const fs = require('fs');
const path = require('path');
const {features} = require('../src/data/features');
const landing = require('../src/data/landing');

const siteDir = path.resolve(__dirname, '..');
const mediaDir = path.join(siteDir, 'static', 'media');
const exts = ['.webp', '.png', '.jpg', '.jpeg', '.mp4', '.webm', '.gif'];

/** id -> {id, type, pages, what, brief, seconds, kind} */
const items = new Map();
function add(entry, page) {
  const have = items.get(entry.id);
  if (have) {
    if (!have.pages.includes(page)) have.pages.push(page);
    return;
  }
  items.set(entry.id, {...entry, pages: [page]});
}
const shot = (s, page) => add({id: s.id, type: 'screenshot', what: s.capture, alt: s.alt}, page);
const video = (v, page, alt) => add({id: v.id, type: 'video', what: v.brief, alt: alt || v.note, seconds: v.seconds, kind: v.kind, youtube: v.youtube}, page);

shot(landing.hero, 'Landing');
for (const c of landing.playClips) add({id: c.id, type: 'clip', what: c.capture, alt: c.alt, seconds: c.seconds, kind: 'capture'}, 'Landing');
video(landing.trailer, 'Landing', landing.trailer.note);
for (const s of landing.starterShots) shot(s, 'Starter');
for (const s of landing.statsShots) shot(s, 'Tsum Tsum Stats');
for (const f of features) {
  const page = `Features / ${f.title}`;
  if (f.hero) {
    shot(f.hero, page);
    if (landing.landingFeatureKeys.includes(f.key)) add({...items.get(f.hero.id)}, 'Landing');
  }
  for (const st of f.steps) {
    if (st.shot) shot(st.shot, page);
    if (st.annotated) shot(st.annotated.shot, page);
  }
  for (const s of f.shots) shot(s, page);
  if (f.video) video(f.video, page);
}

// Ids the source names that nothing declares.
const declared = new Set(items.keys());
const missing = [];
function scan(dir) {
  for (const e of fs.readdirSync(dir, {withFileTypes: true})) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) scan(p);
    else if (/\.(tsx?|mdx?)$/.test(e.name)) {
      for (const m of fs.readFileSync(p, 'utf8').matchAll(/['"`]((?:shot|clip|vid)-[a-z0-9-]+)['"`]/g)) {
        if (!declared.has(m[1])) missing.push(`${path.relative(siteDir, p)}: ${m[1]}`);
      }
    }
  }
}
scan(path.join(siteDir, 'src'));
scan(path.join(siteDir, 'docs'));

const index = {};
for (const id of declared) {
  for (const ext of exts) {
    if (fs.existsSync(path.join(mediaDir, id + ext))) {
      index[id] = '/media/' + id + ext;
      break;
    }
  }
}

if (process.argv.includes('--check')) {
  if (missing.length) {
    console.error('Media ids used but not declared:\n  ' + missing.join('\n  '));
    process.exit(1);
  }
  console.log(`media: ${declared.size} declared, ${Object.keys(index).length} present`);
  process.exit(0);
}

fs.writeFileSync(
  path.join(siteDir, 'src', 'data', 'mediaFiles.generated.json'),
  JSON.stringify(index, null, 2) + '\n',
);

const row = (it) => {
  const done = index[it.id] ? 'done' : it.youtube ? 'on YouTube' : 'needed';
  const len = it.seconds ? ` (${it.seconds}s)` : '';
  const kind = it.kind === 'remotion' ? ' **Remotion.**' : '';
  return `| \`${it.id}\` | ${it.type}${len} | ${it.pages.join('; ')} | ${kind} ${it.what.replace(/\|/g, '/')} | ${done} |`;
};
const head = '| Id | Type | Used on | What | Status |\n|:--|:--|:--|:--|:--|';
const all = [...items.values()];
const byType = (t) => all.filter((i) => i.type === t);
const remotion = all.filter((i) => i.kind === 'remotion');
const left = all.filter((i) => !index[i.id] && !i.youtube).length;

const out = `# Media plan

Generated by \`npm run media:plan\` from \`src/data/features.js\` and
\`src/data/landing.js\`. Do not edit by hand: change the data and regenerate.
**${all.length} items, ${left} still needed.**

Every page already shows a labelled placeholder for each id below. Drop the
finished file into \`static/media/<id>.<ext>\`, run \`npm run media:plan\`, and the
page uses it. No page edit.

## Capture conventions

- **Device:** the emulator or phone in the game's **portrait** orientation, at
  native resolution (1080x1920 preferred). Same device and theme for every
  screenshot so the set looks like one product.
- **Account:** a test account. No friend names, player ids or purchases on screen.
  Blur or crop if it cannot be avoided.
- **Screenshots:** PNG, uncropped unless the row says crop. Convert to WebP for the
  site (\`cwebp -q 90\`); the file is named \`<id>.webp\`.
- **Raw clips:** MP4 (H.264), no audio, 30 fps, loopable where noted. Named \`<id>.mp4\`.
- **Game art:** only your own gameplay captures. Do not add official logos or
  character art that is not in the capture itself.
- **Settings screenshots:** light theme, language English, same preset loaded.

## Remotion

Trailers and instructional videos are built as Remotion compositions in a
\`video/\` project beside the site (\`npm run video:studio\`, \`npm run video:render\`). Built so far: \`vid-trailer\`, \`vid-skills\`, \`vid-autoplay\` and \`vid-levels\`. Plan:

- **One composition per \`vid-*\` id**, same name, 1080x1920 for single-feature
  walkthroughs (they play inside a phone frame) and 1920x1080 for the trailer.
  Output \`static/media/<id>.mp4\`.
- **Shared elements to build once:** step badge (1, 2, 3), arrow/callout, highlight
  ring, lower-third caption, felt coin/medal stickers, the site's colours and
  Caprasimo/Figtree type, a counter (coins, hearts, rounds), and a phone frame.
- **Inputs:** raw captures from the clips list below. Capture once, reuse in several
  compositions.
- **Instructional rule:** every walkthrough shows the *tap or setting* before the
  *result*, with a callout, so it works muted.

Compositions to build (${remotion.length}):

${remotion.map((i) => `- \`${i.id}\` (${i.seconds}s): ${i.what}`).join('\n')}

## Raw captures needed for gameplay clips

${byType('clip').map((i) => `- \`${i.id}\` (${i.seconds}s): ${i.what}`).join('\n')}

## Screenshots

${head}
${byType('screenshot').map(row).join('\n')}

## Clips

${head}
${byType('clip').map(row).join('\n')}

## Videos

${head}
${byType('video').map(row).join('\n')}
`;
fs.writeFileSync(path.join(siteDir, 'MEDIA_PLAN.md'), out);
console.log(`media: wrote MEDIA_PLAN.md (${all.length} items, ${left} needed)`);
